export const GET_LATEST_MOVIE_SUCCESS = 'GET_LATEST_MOVIE_SUCCESS';
export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL';
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
